#!/usr/bin/env python3
"""P2Rank pocket prediction → Vina box config."""

from __future__ import annotations

import argparse
import csv
import shutil
import subprocess
import sys
from pathlib import Path


def run_p2rank(pdb_file: Path, out_dir: Path):
    if shutil.which("prank") is None:
        raise RuntimeError(
            "prank (P2Rank) not on PATH. Install P2Rank or set the docking box manually."
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        "prank",
        "predict",
        "-f",
        str(pdb_file),
        "-o",
        str(out_dir),
        "-visualizations",
        "0",
    ]
    print("[*] Running P2Rank...")
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(f"P2Rank failed: {(r.stderr or r.stdout or '')[:500]}")
    print("[+] P2Rank finished")


def parse_top_pocket(predictions_csv: Path, rank: int = 1):
    with open(predictions_csv) as f:
        reader = csv.DictReader(f)
        # strip spaces from headers
        rows = []
        for row in reader:
            rows.append({(k or "").strip(): (v or "").strip() for k, v in row.items()})
    if not rows:
        raise RuntimeError("No pockets predicted")
    idx = max(0, min(rank - 1, len(rows) - 1))
    top = rows[idx]

    def getf(*keys):
        for k in keys:
            for rk, rv in top.items():
                if rk.lower() == k.lower():
                    return float(rv)
        raise KeyError(keys)

    center = (getf("center_x"), getf("center_y"), getf("center_z"))
    print(f"[+] Pocket rank {idx+1} center: {center[0]:.2f}, {center[1]:.2f}, {center[2]:.2f}")
    return center


def write_vina_config(center, size, config_path: Path, exhaustiveness=32):
    content = f"""# Auto-generated by predict_pocket.py (P2Rank)
center_x = {center[0]:.3f}
center_y = {center[1]:.3f}
center_z = {center[2]:.3f}

size_x = {size}
size_y = {size}
size_z = {size}

exhaustiveness = {exhaustiveness}
num_modes = 20
energy_range = 3
"""
    config_path.write_text(content)
    print(f"[+] Vina config written to {config_path}")


def main(argv=None):
    parser = argparse.ArgumentParser(description="P2Rank pocket prediction → Vina box")
    parser.add_argument("--receptor", required=True)
    parser.add_argument("--out", default="results/pockets")
    parser.add_argument("--top", type=int, default=1)
    parser.add_argument("--size", type=float, default=22.0)
    parser.add_argument("--exhaustiveness", type=int, default=32)
    args = parser.parse_args(argv)

    try:
        receptor = Path(args.receptor)
        if not receptor.exists():
            raise FileNotFoundError(f"receptor not found: {receptor}")
        out_dir = Path(args.out)
        run_p2rank(receptor, out_dir)
        pred_files = list(out_dir.glob("*_predictions.csv")) or list(
            out_dir.rglob("*_predictions.csv")
        )
        if not pred_files:
            raise FileNotFoundError("Could not find P2Rank *_predictions.csv")
        center = parse_top_pocket(pred_files[0], args.top)
        config_path = out_dir / "vina_config_from_p2rank.txt"
        write_vina_config(center, args.size, config_path, args.exhaustiveness)
        print(f"\nNext: python scripts/run_docking.py --receptor {receptor} --ligand ... --config {config_path}")
        return 0
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
