#!/usr/bin/env python3
"""
Run P2Rank to predict ligand binding pockets and generate a Vina config file.

Requires `prank` (P2Rank) to be installed and in PATH.
See: https://github.com/rdk/p2rank
"""

import argparse
import csv
import subprocess
from pathlib import Path


def run_p2rank(pdb_file: Path, out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        "prank", "predict",
        "-f", str(pdb_file),
        "-o", str(out_dir),
        "-visualizations", "0"   # disable heavy visualizations for speed
    ]
    print("[*] Running P2Rank...")
    subprocess.run(cmd, check=True)
    print("[+] P2Rank finished")


def parse_top_pocket(predictions_csv: Path):
    """Read the top-ranked pocket center from P2Rank *_predictions.csv"""
    with open(predictions_csv) as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if not rows:
        raise RuntimeError("No pockets predicted")

    top = rows[0]  # already ranked by score
    center = (
        float(top["center_x"]),
        float(top["center_y"]),
        float(top["center_z"])
    )
    score = float(top.get("score", top.get("probability", 0)))
    print(f"[+] Top pocket score/probability: {score:.3f}")
    print(f"    Center: {center[0]:.2f}, {center[1]:.2f}, {center[2]:.2f}")
    return center


def write_vina_config(center, size, config_path: Path, exhaustiveness=32):
    content = f"""# Auto-generated by predict_pocket.py (P2Rank)
center_x = {center[0]:.3f}
center_y = {center[1]:.3f}
center_z = {center[2]:.3f}

size_x = {size}
size_y = {size}
size_z = {size}

exhaustiveness = {exhaustiveness}
num_modes = 20
energy_range = 3
"""
    config_path.write_text(content)
    print(f"[+] Vina config written to {config_path}")


def main():
    parser = argparse.ArgumentParser(description="P2Rank pocket prediction → Vina box")
    parser.add_argument("--receptor", required=True, help="Input protein PDB")
    parser.add_argument("--out", default="results/pockets", help="Output directory")
    parser.add_argument("--top", type=int, default=1, help="Which ranked pocket to use (1 = best)")
    parser.add_argument("--size", type=float, default=22.0, help="Box size in Å (cubic)")
    parser.add_argument("--exhaustiveness", type=int, default=32)
    args = parser.parse_args()

    receptor = Path(args.receptor)
    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    # Run P2Rank
    run_p2rank(receptor, out_dir)

    # Find the predictions file
    pred_files = list(out_dir.glob("*_predictions.csv"))
    if not pred_files:
        # Sometimes P2Rank puts them in a subdirectory
        pred_files = list(out_dir.rglob("*_predictions.csv"))
    if not pred_files:
        raise FileNotFoundError("Could not find P2Rank *_predictions.csv")

    pred_csv = pred_files[0]
    center = parse_top_pocket(pred_csv)

    config_path = out_dir / "vina_config_from_p2rank.txt"
    write_vina_config(center, args.size, config_path, args.exhaustiveness)

    print("\nNext step:")
    print(f"  python scripts/run_docking.py --receptor {receptor} --ligand ... --config {config_path}")


if __name__ == "__main__":
    main()
